#############################################################################
# Makefile for building: Amiga
# Generated by qmake (2.01a) (Qt 4.8.1) on: Thu Aug 23 19:05:05 2012
# Project:  Source/Amiga.pro
# Template: app
# Command: /usr/bin/qmake CONFIG+=Amiga -o Makefile Source/Amiga.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -ISource -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -ISource -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./Source

####### Files

SOURCES       = /Source/main.cpp \
		/Source/amiga.cpp \
		/Source/configchipset.cpp \
		/Source/configram.cpp \
		/Source/configfloppy.cpp \
		/Source/configcdrom.cpp \
		/Source/configharddisks.cpp \
		/Source/configgraphics.cpp \
		/Source/configmisc.cpp \
		/Source/configtheme.cpp \
		/Source/configinput.cpp moc_amiga.cpp \
		/qrc_ICO.cpp
OBJECTS       = main.o \
		amiga.o \
		configchipset.o \
		configram.o \
		configfloppy.o \
		configcdrom.o \
		configharddisks.o \
		configgraphics.o \
		configmisc.o \
		configtheme.o \
		configinput.o \
		moc_amiga.o \
		qrc_ICO.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Source/Amiga.pro
QMAKE_TARGET  = Amiga
DESTDIR       = 
TARGET        = Amiga

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_amiga.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Source/Amiga.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) CONFIG+=Amiga -o Makefile Source/Amiga.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) CONFIG+=Amiga -o Makefile Source/Amiga.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Amiga1.0.0 || $(MKDIR) .tmp/Amiga1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Amiga1.0.0/ && $(COPY_FILE) --parents Source/amiga.h Source/configchipset.h Source/configram.h Source/configfloppy.h Source/configcdrom.h Source/configharddisks.h Source/configgraphics.h Source/configmisc.h Source/configtheme.h Source/configinput.h .tmp/Amiga1.0.0/ && $(COPY_FILE) --parents Source/ICO.qrc .tmp/Amiga1.0.0/ && $(COPY_FILE) --parents Source/main.cpp Source/amiga.cpp Source/configchipset.cpp Source/configram.cpp Source/configfloppy.cpp Source/configcdrom.cpp Source/configharddisks.cpp Source/configgraphics.cpp Source/configmisc.cpp Source/configtheme.cpp Source/configinput.cpp .tmp/Amiga1.0.0/ && $(COPY_FILE) --parents Source/amiga.ui .tmp/Amiga1.0.0/ && (cd `dirname .tmp/Amiga1.0.0` && $(TAR) Amiga1.0.0.tar Amiga1.0.0 && $(COMPRESS) Amiga1.0.0.tar) && $(MOVE) `dirname .tmp/Amiga1.0.0`/Amiga1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Amiga1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_amiga.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_amiga.cpp
moc_amiga.cpp: Source/configchipset.h \
		Source/configram.h \
		Source/configfloppy.h \
		Source/configcdrom.h \
		Source/configharddisks.h \
		Source/configgraphics.h \
		Source/configinput.h \
		Source/configtheme.h \
		Source/configmisc.h \
		Source/amiga.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Source/amiga.h -o moc_amiga.cpp

compiler_rcc_make_all: qrc_ICO.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ICO.cpp
qrc_ICO.cpp: Source/ICO.qrc
	/usr/bin/rcc -name ICO Source/ICO.qrc -o qrc_ICO.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_amiga.h
compiler_uic_clean:
	-$(DEL_FILE) ui_amiga.h
ui_amiga.h: Source/amiga.ui
	/usr/bin/uic-qt4 Source/amiga.ui -o ui_amiga.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: Source/main.cpp Source/amiga.h \
		Source/configchipset.h \
		Source/configram.h \
		Source/configfloppy.h \
		Source/configcdrom.h \
		Source/configharddisks.h \
		Source/configgraphics.h \
		Source/configinput.h \
		Source/configtheme.h \
		Source/configmisc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Source/main.cpp

amiga.o: Source/amiga.cpp Source/amiga.h \
		Source/configchipset.h \
		Source/configram.h \
		Source/configfloppy.h \
		Source/configcdrom.h \
		Source/configharddisks.h \
		Source/configgraphics.h \
		Source/configinput.h \
		Source/configtheme.h \
		Source/configmisc.h \
		Source/ui_amiga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o amiga.o Source/amiga.cpp

configchipset.o: Source/configchipset.cpp Source/configchipset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configchipset.o Source/configchipset.cpp

configram.o: Source/configram.cpp Source/configram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configram.o Source/configram.cpp

configfloppy.o: Source/configfloppy.cpp Source/configfloppy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configfloppy.o Source/configfloppy.cpp

configcdrom.o: Source/configcdrom.cpp Source/configcdrom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configcdrom.o Source/configcdrom.cpp

configharddisks.o: Source/configharddisks.cpp Source/configharddisks.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configharddisks.o Source/configharddisks.cpp

configgraphics.o: Source/configgraphics.cpp Source/configgraphics.h \
		Source/amiga.h \
		Source/configchipset.h \
		Source/configram.h \
		Source/configfloppy.h \
		Source/configcdrom.h \
		Source/configharddisks.h \
		Source/configinput.h \
		Source/configtheme.h \
		Source/configmisc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configgraphics.o Source/configgraphics.cpp

configmisc.o: Source/configmisc.cpp Source/configmisc.h \
		Source/amiga.h \
		Source/configchipset.h \
		Source/configram.h \
		Source/configfloppy.h \
		Source/configcdrom.h \
		Source/configharddisks.h \
		Source/configgraphics.h \
		Source/configinput.h \
		Source/configtheme.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configmisc.o Source/configmisc.cpp

configtheme.o: Source/configtheme.cpp Source/configtheme.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configtheme.o Source/configtheme.cpp

configinput.o: Source/configinput.cpp Source/configinput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configinput.o Source/configinput.cpp

moc_amiga.o: moc_amiga.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_amiga.o moc_amiga.cpp

qrc_ICO.o: qrc_ICO.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ICO.o qrc_ICO.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

