.TH "amiga.h" 3 "Thu Aug 23 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
amiga.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include <configchipset\&.h>\fP
.br
\fC#include <configram\&.h>\fP
.br
\fC#include <configfloppy\&.h>\fP
.br
\fC#include <configcdrom\&.h>\fP
.br
\fC#include <configharddisks\&.h>\fP
.br
\fC#include <configgraphics\&.h>\fP
.br
\fC#include <configinput\&.h>\fP
.br
\fC#include <configtheme\&.h>\fP
.br
\fC#include <configmisc\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAmiga\fP"
.br
.RI "\fIThis class is responsible for the magement of FS-UAE Gui\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
