.TH "ConfigGraphics" 3 "Thu Aug 23 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigGraphics \- 
.PP
This class is responsible for the Graphics Configuration management\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <configgraphics\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigGraphics\fP ()"
.br
.ti -1c
.RI "string \fBgetFullscreenConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetFullscreenString\fP ()"
.br
.ti -1c
.RI "string \fBgetFullscreenWidthConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetFullscreenWidthString\fP ()"
.br
.ti -1c
.RI "string \fBgetFullscreenHeightConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetFullscreenHeightString\fP ()"
.br
.ti -1c
.RI "string \fBgetWindowWidthConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetWindowWidthString\fP ()"
.br
.ti -1c
.RI "string \fBgetWindowHeightConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetWindowHeightString\fP ()"
.br
.ti -1c
.RI "string \fBgetWindowResizableConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetWindowResizableString\fP ()"
.br
.ti -1c
.RI "string \fBgetFsaaConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetFsaaString\fP ()"
.br
.ti -1c
.RI "string \fBgetKeepAspectConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetKeepAspectString\fP ()"
.br
.ti -1c
.RI "string \fBgetScanlinesConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetScanlinesString\fP ()"
.br
.ti -1c
.RI "string \fBgetRtgScanlinesConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetRtgScanlinesString\fP ()"
.br
.ti -1c
.RI "string \fBgetScanlinesDarkConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetScanlinesDarkString\fP ()"
.br
.ti -1c
.RI "string \fBgetScanlinesLightConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetScanlinesLightString\fP ()"
.br
.ti -1c
.RI "string \fBgetShaderConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetShaderString\fP ()"
.br
.ti -1c
.RI "string \fBgetLowResolutionConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetLowResolutionString\fP ()"
.br
.ti -1c
.RI "string \fBgetLineDoublingConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetLineDoublingString\fP ()"
.br
.ti -1c
.RI "string \fBgetScaleXConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetScaleXString\fP ()"
.br
.ti -1c
.RI "string \fBgetScaleYConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetScaleYString\fP ()"
.br
.ti -1c
.RI "string \fBgetAlignXConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetAlignXString\fP ()"
.br
.ti -1c
.RI "string \fBgetAlignYConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetAlignYString\fP ()"
.br
.ti -1c
.RI "string \fBgetZoomConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetZoomString\fP ()"
.br
.ti -1c
.RI "string \fBgetTextureFilterConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetTextureFilterString\fP ()"
.br
.ti -1c
.RI "string \fBgetVideoSyncConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetVideoSyncString\fP ()"
.br
.ti -1c
.RI "string \fBgetVideoSyncMethodConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetVideoSyncMethodString\fP ()"
.br
.ti -1c
.RI "string \fBgetVideoFormatConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetVideoFormatString\fP ()"
.br
.ti -1c
.RI "string \fBgetTextureFormatConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetTextureFormatString\fP ()"
.br
.ti -1c
.RI "bool \fBcontainsViewport\fP (string s)"
.br
.ti -1c
.RI "int \fBgetViewportSize\fP ()"
.br
.ti -1c
.RI "string \fBgetViewportAt\fP (int position)"
.br
.ti -1c
.RI "void \fBeraseViewportAt\fP (int position)"
.br
.ti -1c
.RI "int \fBsetParameter\fP (string parameter, string value)"
.br
.ti -1c
.RI "void \fBsetToDefaultConfiguration\fP ()"
.br
.ti -1c
.RI "bool \fBhasParameter\fP (string parameterName)"
.br
.ti -1c
.RI "bool \fBisValidViewport\fP (string viewportString)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "string \fBfullscreen\fP"
.br
.ti -1c
.RI "string \fBfullscreen_width\fP"
.br
.ti -1c
.RI "string \fBfullscreen_height\fP"
.br
.ti -1c
.RI "string \fBwindow_width\fP"
.br
.ti -1c
.RI "string \fBwindow_height\fP"
.br
.ti -1c
.RI "string \fBwindow_resizable\fP"
.br
.ti -1c
.RI "string \fBfsaa\fP"
.br
.ti -1c
.RI "string \fBkeep_aspect\fP"
.br
.ti -1c
.RI "string \fBscanlines\fP"
.br
.ti -1c
.RI "string \fBrtg_scanlines\fP"
.br
.ti -1c
.RI "string \fBscanlines_dark\fP"
.br
.ti -1c
.RI "string \fBscanlines_light\fP"
.br
.ti -1c
.RI "string \fBshader\fP"
.br
.ti -1c
.RI "string \fBlow_resolution\fP"
.br
.ti -1c
.RI "string \fBline_doubling\fP"
.br
.ti -1c
.RI "string \fBscale_x\fP"
.br
.ti -1c
.RI "string \fBscale_y\fP"
.br
.ti -1c
.RI "string \fBalign_x\fP"
.br
.ti -1c
.RI "string \fBalign_y\fP"
.br
.ti -1c
.RI "string \fBzoom\fP"
.br
.ti -1c
.RI "string \fBtexture_filter\fP"
.br
.ti -1c
.RI "string \fBvideo_sync\fP"
.br
.ti -1c
.RI "string \fBvideo_sync_method\fP"
.br
.ti -1c
.RI "string \fBvideo_format\fP"
.br
.ti -1c
.RI "string \fBtexture_format\fP"
.br
.ti -1c
.RI "vector< string > \fBviewport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is responsible for the Graphics Configuration management\&. 

In this class are defined all the variables for the correct management of graphics configuration's tab\&.
.br
 This board is composed of 4 parts: the first section with the DISPLAY SETTINGS, the second FILTERS, SHADERS AND SCALING, the third VIDEO SYNCHRONIZATION, and fourth VIDEO AND TEXTURE BUFFER FORMAT\&.
.br
 DISPLAY SETTINGS: you can change for startup fullscreen mode and make possible the resizing window, change fullscreen and window resolution and enable full-scene anti-aliasing\&.
.br
 FILTERS, SHADERS AND SCALING: in this section are all the settings relating scanlines (enable, RTG and variation of light and dark), type of shaders, resolution and line doubling\&.
.br
 Here are also managed the position and alignment of the texture as well as their filtering and how to start the video emulation\&.
.br
 VIDEO SYNCHRONIZATION: here you can select type and methode of syncronization\&.
.br
 VIDEO AND TEXTURE BUFFER FORMAT: here you can select video and texture format\&.
.br
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBConfigGraphics::ConfigGraphics\fP ()"
.SH "Member Function Documentation"
.PP 
.SS "bool \fBConfigGraphics::containsViewport\fP (strings)"
.SS "void \fBConfigGraphics::eraseViewportAt\fP (intposition)"
.SS "string \fBConfigGraphics::getAlignXConfigString\fP ()"
.SS "string \fBConfigGraphics::getAlignXString\fP ()"
.SS "string \fBConfigGraphics::getAlignYConfigString\fP ()"
.SS "string \fBConfigGraphics::getAlignYString\fP ()"
.SS "string \fBConfigGraphics::getFsaaConfigString\fP ()"
.SS "string \fBConfigGraphics::getFsaaString\fP ()"
.SS "string \fBConfigGraphics::getFullscreenConfigString\fP ()"
.SS "string \fBConfigGraphics::getFullscreenHeightConfigString\fP ()"
.SS "string \fBConfigGraphics::getFullscreenHeightString\fP ()"
.SS "string \fBConfigGraphics::getFullscreenString\fP ()"
.SS "string \fBConfigGraphics::getFullscreenWidthConfigString\fP ()"
.SS "string \fBConfigGraphics::getFullscreenWidthString\fP ()"
.SS "string \fBConfigGraphics::getKeepAspectConfigString\fP ()"
.SS "string \fBConfigGraphics::getKeepAspectString\fP ()"
.SS "string \fBConfigGraphics::getLineDoublingConfigString\fP ()"
.SS "string \fBConfigGraphics::getLineDoublingString\fP ()"
.SS "string \fBConfigGraphics::getLowResolutionConfigString\fP ()"
.SS "string \fBConfigGraphics::getLowResolutionString\fP ()"
.SS "string \fBConfigGraphics::getRtgScanlinesConfigString\fP ()"
.SS "string \fBConfigGraphics::getRtgScanlinesString\fP ()"
.SS "string \fBConfigGraphics::getScaleXConfigString\fP ()"
.SS "string \fBConfigGraphics::getScaleXString\fP ()"
.SS "string \fBConfigGraphics::getScaleYConfigString\fP ()"
.SS "string \fBConfigGraphics::getScaleYString\fP ()"
.SS "string \fBConfigGraphics::getScanlinesConfigString\fP ()"
.SS "string \fBConfigGraphics::getScanlinesDarkConfigString\fP ()"
.SS "string \fBConfigGraphics::getScanlinesDarkString\fP ()"
.SS "string \fBConfigGraphics::getScanlinesLightConfigString\fP ()"
.SS "string \fBConfigGraphics::getScanlinesLightString\fP ()"
.SS "string \fBConfigGraphics::getScanlinesString\fP ()"
.SS "string \fBConfigGraphics::getShaderConfigString\fP ()"
.SS "string \fBConfigGraphics::getShaderString\fP ()"
.SS "string \fBConfigGraphics::getTextureFilterConfigString\fP ()"
.SS "string \fBConfigGraphics::getTextureFilterString\fP ()"
.SS "string \fBConfigGraphics::getTextureFormatConfigString\fP ()"
.SS "string \fBConfigGraphics::getTextureFormatString\fP ()"
.SS "string \fBConfigGraphics::getVideoFormatConfigString\fP ()"
.SS "string \fBConfigGraphics::getVideoFormatString\fP ()"
.SS "string \fBConfigGraphics::getVideoSyncConfigString\fP ()"
.SS "string \fBConfigGraphics::getVideoSyncMethodConfigString\fP ()"
.SS "string \fBConfigGraphics::getVideoSyncMethodString\fP ()"
.SS "string \fBConfigGraphics::getVideoSyncString\fP ()"
.SS "string \fBConfigGraphics::getViewportAt\fP (intposition)"
.SS "int \fBConfigGraphics::getViewportSize\fP ()"
.SS "string \fBConfigGraphics::getWindowHeightConfigString\fP ()"
.SS "string \fBConfigGraphics::getWindowHeightString\fP ()"
.SS "string \fBConfigGraphics::getWindowResizableConfigString\fP ()"
.SS "string \fBConfigGraphics::getWindowResizableString\fP ()"
.SS "string \fBConfigGraphics::getWindowWidthConfigString\fP ()"
.SS "string \fBConfigGraphics::getWindowWidthString\fP ()"
.SS "string \fBConfigGraphics::getZoomConfigString\fP ()"
.SS "string \fBConfigGraphics::getZoomString\fP ()"
.SS "bool \fBConfigGraphics::hasParameter\fP (stringparameterName)"
.SS "bool \fBConfigGraphics::isValidViewport\fP (stringviewportString)"
.SS "int \fBConfigGraphics::setParameter\fP (stringparameter, stringvalue)"
.SS "void \fBConfigGraphics::setToDefaultConfiguration\fP ()"
.SH "Member Data Documentation"
.PP 
.SS "string \fBConfigGraphics::align_x\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::align_y\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::fsaa\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::fullscreen\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::fullscreen_height\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::fullscreen_width\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::keep_aspect\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::line_doubling\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::low_resolution\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::rtg_scanlines\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::scale_x\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::scale_y\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::scanlines\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::scanlines_dark\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::scanlines_light\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::shader\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::texture_filter\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::texture_format\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::video_format\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::video_sync\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::video_sync_method\fP\fC [private]\fP"
.SS "vector<string> \fBConfigGraphics::viewport\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::window_height\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::window_resizable\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::window_width\fP\fC [private]\fP"
.SS "string \fBConfigGraphics::zoom\fP\fC [private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
