.TH "configgraphics.cpp" 3 "Thu Aug 23 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configgraphics.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'configgraphics\&.h'\fP
.br
\fC#include 'amiga\&.h'\fP
.br
\fC#include <sstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static bool \fBisNumber\fP (string s)"
.br
.ti -1c
.RI "static bool \fBisFloat\fP (string line)"
.br
.ti -1c
.RI "static int \fBstrToInt\fP (string s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const string \fBDEFAULTFULLSCREEN\fP = '0'"
.br
.ti -1c
.RI "const string \fBDEFAULTFULLSCREENWIDTH\fP = ''"
.br
.ti -1c
.RI "const string \fBDEFAULTFULLSCREENHEIGHT\fP = ''"
.br
.ti -1c
.RI "const string \fBDEFAULTWINDOWWIDTH\fP = '960'"
.br
.ti -1c
.RI "const string \fBDEFAULTWINDOWHEIGHT\fP = '540'"
.br
.ti -1c
.RI "const string \fBDEFAULTWINDOWRESIZABLE\fP = '1'"
.br
.ti -1c
.RI "const string \fBDEFAULTFSAA\fP = '0'"
.br
.ti -1c
.RI "const string \fBDEFAULTKEEPASPECT\fP = '0'"
.br
.ti -1c
.RI "const string \fBDEFAULTSCANLINES\fP = '0'"
.br
.ti -1c
.RI "const string \fBDEFAULTRTGSCANLINES\fP = '0'"
.br
.ti -1c
.RI "const string \fBDEFAULTSCANLINESDARK\fP = '10'"
.br
.ti -1c
.RI "const string \fBDEFAULTSCANLINESLIGHT\fP = '5'"
.br
.ti -1c
.RI "const string \fBDEFAULTSHADER\fP = ''"
.br
.ti -1c
.RI "const string \fBDEFAULTLOWRESOLUTION\fP = '0'"
.br
.ti -1c
.RI "const string \fBDEFAULTLINEDOUBLING\fP = '1'"
.br
.ti -1c
.RI "const string \fBDEFAULTSCALEX\fP = '-1\&.0'"
.br
.ti -1c
.RI "const string \fBDEFAULTSCALEY\fP = '-1\&.0'"
.br
.ti -1c
.RI "const string \fBDEFAULTALIGNX\fP = '0\&.5'"
.br
.ti -1c
.RI "const string \fBDEFAULTALIGNY\fP = '0\&.5'"
.br
.ti -1c
.RI "const string \fBDEFAULTZOOM\fP = 'auto'"
.br
.ti -1c
.RI "const string \fBDEFAULTTEXTUREFILTER\fP = 'linear'"
.br
.ti -1c
.RI "const string \fBDEFAULTVIDEOSYNC\fP = 'auto'"
.br
.ti -1c
.RI "const string \fBDEFAULTVIDEOSYNCMETHOD\fP = 'finish-swap-finish'"
.br
.ti -1c
.RI "const string \fBDEFAULTVIDEOFORMAT\fP = 'bgra'"
.br
.ti -1c
.RI "const string \fBDEFAULTTEXTUREFORMAT\fP = 'rgb'"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBconfiggraphics\&.cpp\fP
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc\&., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA\&. Written by Riva Alessandro Mario, alessandromario.riva@gmail.com and Sanvito Davide, dsanvito90@gmail.com\&. 
.SH "Function Documentation"
.PP 
.SS "static bool \fBisFloat\fP (stringline)\fC [static]\fP"
.SS "static bool \fBisNumber\fP (strings)\fC [static]\fP"
.SS "static int \fBstrToInt\fP (strings)\fC [static]\fP"
.SH "Variable Documentation"
.PP 
.SS "const string \fBDEFAULTALIGNX\fP = '0\&.5'"
.SS "const string \fBDEFAULTALIGNY\fP = '0\&.5'"
.SS "const string \fBDEFAULTFSAA\fP = '0'"
.SS "const string \fBDEFAULTFULLSCREEN\fP = '0'"
.SS "const string \fBDEFAULTFULLSCREENHEIGHT\fP = ''"
.SS "const string \fBDEFAULTFULLSCREENWIDTH\fP = ''"
.SS "const string \fBDEFAULTKEEPASPECT\fP = '0'"
.SS "const string \fBDEFAULTLINEDOUBLING\fP = '1'"
.SS "const string \fBDEFAULTLOWRESOLUTION\fP = '0'"
.SS "const string \fBDEFAULTRTGSCANLINES\fP = '0'"
.SS "const string \fBDEFAULTSCALEX\fP = '-1\&.0'"
.SS "const string \fBDEFAULTSCALEY\fP = '-1\&.0'"
.SS "const string \fBDEFAULTSCANLINES\fP = '0'"
.SS "const string \fBDEFAULTSCANLINESDARK\fP = '10'"
.SS "const string \fBDEFAULTSCANLINESLIGHT\fP = '5'"
.SS "const string \fBDEFAULTSHADER\fP = ''"
.SS "const string \fBDEFAULTTEXTUREFILTER\fP = 'linear'"
.SS "const string \fBDEFAULTTEXTUREFORMAT\fP = 'rgb'"
.SS "const string \fBDEFAULTVIDEOFORMAT\fP = 'bgra'"
.SS "const string \fBDEFAULTVIDEOSYNC\fP = 'auto'"
.SS "const string \fBDEFAULTVIDEOSYNCMETHOD\fP = 'finish-swap-finish'"
.SS "const string \fBDEFAULTWINDOWHEIGHT\fP = '540'"
.SS "const string \fBDEFAULTWINDOWRESIZABLE\fP = '1'"
.SS "const string \fBDEFAULTWINDOWWIDTH\fP = '960'"
.SS "const string \fBDEFAULTZOOM\fP = 'auto'"
.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
