.TH "amiga.cpp" 3 "Tue Aug 21 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
amiga.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'amiga\&.h'\fP
.br
\fC#include 'ui_amiga\&.h'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <QUrl>\fP
.br
\fC#include <QDesktopServices>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QColorDialog>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <QKeyEvent>\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QDesktopWidget>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBshowAlert\fP (string message)"
.br
.ti -1c
.RI "static void \fBcheckFoldersExistence\fP ()"
.br
.ti -1c
.RI "int \fBstrToInt\fP (string s)"
.br
.ti -1c
.RI "float \fBstrToFloat\fP (string line)"
.br
.ti -1c
.RI "string \fBintToStr\fP (int n)"
.br
.ti -1c
.RI "bool \fBisEmptyString\fP (string s)"
.br
.ti -1c
.RI "QString \fBgetAmigaKeyboardKeysFromKey\fP (int key)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const QString \fBpro\fP = 'of INI Custom Controller Configuration file\&.'"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBamiga\&.cpp\fP
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc\&., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA\&. Written by Riva Alessandro Mario, alessandromario.riva@gmail.com and Sanvito Davide, dsanvito90@gmail.com\&. 
.SH "Function Documentation"
.PP 
.SS "static void \fBcheckFoldersExistence\fP ()\fC [static]\fP"
.SS "QString \fBgetAmigaKeyboardKeysFromKey\fP (intkey)"
.SS "string \fBintToStr\fP (intn)"
.SS "bool \fBisEmptyString\fP (strings)"
.SS "static void \fBshowAlert\fP (stringmessage)\fC [static]\fP"
.SS "float \fBstrToFloat\fP (stringline)"
.SS "int \fBstrToInt\fP (strings)"
.SH "Variable Documentation"
.PP 
.SS "const QString \fBpro\fP = 'of INI Custom Controller Configuration file\&.'"
.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
