.TH "amiga.cpp" 3 "Fri Jul 27 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
amiga.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'amiga\&.h'\fP
.br
\fC#include 'ui_amiga\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <QUrl>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <pwd\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <QDesktopServices>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QColorDialog>\fP
.br
\fC#include <QProcess>\fP
.br
\fC#include <cstdlib>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBisEmptyString\fP (string s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool \fBisEmptyString\fP (strings)"
.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
