.TH "configfloppy.cpp" 3 "Wed Aug 22 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configfloppy.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'configfloppy\&.h'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static bool \fBisNumber\fP (string s)"
.br
.ti -1c
.RI "static int \fBstrToInt\fP (string s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const string \fBDEFAULTFLOPPYDRIVE\fP = ''"
.br
.ti -1c
.RI "const string \fBDEFAULTFLOPPYDRIVEVOLUME\fP = '20'"
.br
.ti -1c
.RI "const string \fBDEFAULTFLOPPYDRIVESPEED\fP = '100'"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBconfigfloppy\&.cpp\fP
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc\&., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA\&. Written by Riva Alessandro Mario, alessandromario.riva@gmail.com and Sanvito Davide, dsanvito90@gmail.com\&. 
.SH "Function Documentation"
.PP 
.SS "static bool \fBisNumber\fP (strings)\fC [static]\fP"
.SS "static int \fBstrToInt\fP (strings)\fC [static]\fP"
.SH "Variable Documentation"
.PP 
.SS "const string \fBDEFAULTFLOPPYDRIVE\fP = ''"
.SS "const string \fBDEFAULTFLOPPYDRIVESPEED\fP = '100'"
.SS "const string \fBDEFAULTFLOPPYDRIVEVOLUME\fP = '20'"
.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
