.TH "configram.h" 3 "Sun Aug 19 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configram.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigRam\fP"
.br
.RI "\fIThis class is responsible for the Ram Configuration\&. The default value of each type of ram depends on the selected \fBAmiga\fP model\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
