.TH "ConfigInput" 3 "Thu Aug 23 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigInput \- 
.PP
This class is responsible for the Graphics Configuration management\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <configinput\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigInput\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort0ConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort0String\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort1ConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort1String\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort2ConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort2String\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort3ConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort3String\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort0ModeConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort0ModeString\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort1ModeConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort1ModeString\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort2ModeConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort2ModeString\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort3ModeConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetJoystickPort3ModeString\fP ()"
.br
.ti -1c
.RI "bool \fBcontainsKeyOrAction\fP (string s)"
.br
.ti -1c
.RI "int \fBgetCustomInputMappingSize\fP ()"
.br
.ti -1c
.RI "string \fBgetCustomInputMappingAt\fP (int position)"
.br
.ti -1c
.RI "void \fBeraseCustomInputMappingAt\fP (int position)"
.br
.ti -1c
.RI "int \fBsetParameter\fP (string parameter, string value)"
.br
.ti -1c
.RI "void \fBsetToDefaultConfiguration\fP ()"
.br
.ti -1c
.RI "bool \fBhasParameter\fP (string parameterName)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "string \fBjoystickNumberString\fP (int portNumber)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "vector< string > \fBcustom_input_mapping_inserted_keys\fP"
.br
.ti -1c
.RI "vector< string > \fBcustom_input_mapping_inserted_actions\fP"
.br
.ti -1c
.RI "string \fBjoystick_port_0\fP"
.br
.ti -1c
.RI "string \fBjoystick_port_1\fP"
.br
.ti -1c
.RI "string \fBjoystick_port_2\fP"
.br
.ti -1c
.RI "string \fBjoystick_port_3\fP"
.br
.ti -1c
.RI "string \fBjoystick_port_0_mode\fP"
.br
.ti -1c
.RI "string \fBjoystick_port_1_mode\fP"
.br
.ti -1c
.RI "string \fBjoystick_port_2_mode\fP"
.br
.ti -1c
.RI "string \fBjoystick_port_3_mode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is responsible for the Graphics Configuration management\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBConfigInput::ConfigInput\fP ()"
.SH "Member Function Documentation"
.PP 
.SS "bool \fBConfigInput::containsKeyOrAction\fP (strings)"
.SS "void \fBConfigInput::eraseCustomInputMappingAt\fP (intposition)"
.SS "string \fBConfigInput::getCustomInputMappingAt\fP (intposition)"
.SS "int \fBConfigInput::getCustomInputMappingSize\fP ()"
.SS "string \fBConfigInput::getJoystickPort0ConfigString\fP ()"
.SS "string \fBConfigInput::getJoystickPort0ModeConfigString\fP ()"
.SS "string \fBConfigInput::getJoystickPort0ModeString\fP ()"
.SS "string \fBConfigInput::getJoystickPort0String\fP ()"
.SS "string \fBConfigInput::getJoystickPort1ConfigString\fP ()"
.SS "string \fBConfigInput::getJoystickPort1ModeConfigString\fP ()"
.SS "string \fBConfigInput::getJoystickPort1ModeString\fP ()"
.SS "string \fBConfigInput::getJoystickPort1String\fP ()"
.SS "string \fBConfigInput::getJoystickPort2ConfigString\fP ()"
.SS "string \fBConfigInput::getJoystickPort2ModeConfigString\fP ()"
.SS "string \fBConfigInput::getJoystickPort2ModeString\fP ()"
.SS "string \fBConfigInput::getJoystickPort2String\fP ()"
.SS "string \fBConfigInput::getJoystickPort3ConfigString\fP ()"
.SS "string \fBConfigInput::getJoystickPort3ModeConfigString\fP ()"
.SS "string \fBConfigInput::getJoystickPort3ModeString\fP ()"
.SS "string \fBConfigInput::getJoystickPort3String\fP ()"
.SS "bool \fBConfigInput::hasParameter\fP (stringparameterName)"
.SS "string \fBConfigInput::joystickNumberString\fP (intportNumber)\fC [private]\fP"
.SS "int \fBConfigInput::setParameter\fP (stringparameter, stringvalue)"
.SS "void \fBConfigInput::setToDefaultConfiguration\fP ()"
.SH "Member Data Documentation"
.PP 
.SS "vector<string> \fBConfigInput::custom_input_mapping_inserted_actions\fP\fC [private]\fP"
.SS "vector<string> \fBConfigInput::custom_input_mapping_inserted_keys\fP\fC [private]\fP"
.SS "string \fBConfigInput::joystick_port_0\fP\fC [private]\fP"
.SS "string \fBConfigInput::joystick_port_0_mode\fP\fC [private]\fP"
.SS "string \fBConfigInput::joystick_port_1\fP\fC [private]\fP"
.SS "string \fBConfigInput::joystick_port_1_mode\fP\fC [private]\fP"
.SS "string \fBConfigInput::joystick_port_2\fP\fC [private]\fP"
.SS "string \fBConfigInput::joystick_port_2_mode\fP\fC [private]\fP"
.SS "string \fBConfigInput::joystick_port_3\fP\fC [private]\fP"
.SS "string \fBConfigInput::joystick_port_3_mode\fP\fC [private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
