.TH "configchipset.cpp" 3 "Sun Jul 29 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configchipset.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'configchipset\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const string \fBDEFAULTACCURACY\fP = '1'"
.br
.ti -1c
.RI "const string \fBDEFAULTNTSCMODE\fP = '0'"
.br
.ti -1c
.RI "const string \fBDEFAULTAMIGAMODEL\fP = 'A500'"
.br
.ti -1c
.RI "const string \fBDEFAULTKICKSTARTFILE\fP = ''"
.br
.ti -1c
.RI "const string \fBDEFAULTKICKSTARTEXTFILE\fP = ''"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const string \fBDEFAULTACCURACY\fP = '1'"
.SS "const string \fBDEFAULTAMIGAMODEL\fP = 'A500'"
.SS "const string \fBDEFAULTKICKSTARTEXTFILE\fP = ''"
.SS "const string \fBDEFAULTKICKSTARTFILE\fP = ''"
.SS "const string \fBDEFAULTNTSCMODE\fP = '0'"
.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
