.TH "ConfigTheme" 3 "Wed Aug 22 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigTheme \- 
.PP
This class is responsible for the Theme Configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <configtheme\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigTheme\fP ()"
.br
.ti -1c
.RI "string \fBgetThemeConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetThemeString\fP ()"
.br
.ti -1c
.RI "string \fBgetFadeColorConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetFadeColorString\fP ()"
.br
.ti -1c
.RI "string \fBgetWallColor1ConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetWallColor1String\fP ()"
.br
.ti -1c
.RI "string \fBgetWallColor2ConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetWallColor2String\fP ()"
.br
.ti -1c
.RI "string \fBgetFloorColor1ConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetFloorColor1String\fP ()"
.br
.ti -1c
.RI "string \fBgetFloorColor2ConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetFloorColor2String\fP ()"
.br
.ti -1c
.RI "string \fBgetHeadingColorConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetHeadingColorString\fP ()"
.br
.ti -1c
.RI "string \fBgetOverlayImageConfigString\fP ()"
.br
.ti -1c
.RI "string \fBgetOverlayImageString\fP ()"
.br
.ti -1c
.RI "int \fBsetParameter\fP (string parameter, string value)"
.br
.ti -1c
.RI "void \fBsetToDefaultConfiguration\fP ()"
.br
.ti -1c
.RI "bool \fBhasParameter\fP (string parameterName)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "string \fBtheme\fP"
.br
.ti -1c
.RI "string \fBtheme_fade_color\fP"
.br
.ti -1c
.RI "string \fBtheme_wall_color_1\fP"
.br
.ti -1c
.RI "string \fBtheme_wall_color_2\fP"
.br
.ti -1c
.RI "string \fBtheme_floor_color_1\fP"
.br
.ti -1c
.RI "string \fBtheme_floor_color_2\fP"
.br
.ti -1c
.RI "string \fBtheme_heading_color\fP"
.br
.ti -1c
.RI "string \fBtheme_overlay_image\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is responsible for the Theme Configuration\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBConfigTheme::ConfigTheme\fP ()"
.SH "Member Function Documentation"
.PP 
.SS "string \fBConfigTheme::getFadeColorConfigString\fP ()"
.SS "string \fBConfigTheme::getFadeColorString\fP ()"
.SS "string \fBConfigTheme::getFloorColor1ConfigString\fP ()"
.SS "string \fBConfigTheme::getFloorColor1String\fP ()"
.SS "string \fBConfigTheme::getFloorColor2ConfigString\fP ()"
.SS "string \fBConfigTheme::getFloorColor2String\fP ()"
.SS "string \fBConfigTheme::getHeadingColorConfigString\fP ()"
.SS "string \fBConfigTheme::getHeadingColorString\fP ()"
.SS "string \fBConfigTheme::getOverlayImageConfigString\fP ()"
.SS "string \fBConfigTheme::getOverlayImageString\fP ()"
.SS "string \fBConfigTheme::getThemeConfigString\fP ()"
.SS "string \fBConfigTheme::getThemeString\fP ()"
.SS "string \fBConfigTheme::getWallColor1ConfigString\fP ()"
.SS "string \fBConfigTheme::getWallColor1String\fP ()"
.SS "string \fBConfigTheme::getWallColor2ConfigString\fP ()"
.SS "string \fBConfigTheme::getWallColor2String\fP ()"
.SS "bool \fBConfigTheme::hasParameter\fP (stringparameterName)"
.SS "int \fBConfigTheme::setParameter\fP (stringparameter, stringvalue)"
.SS "void \fBConfigTheme::setToDefaultConfiguration\fP ()"
.SH "Member Data Documentation"
.PP 
.SS "string \fBConfigTheme::theme\fP\fC [private]\fP"
.SS "string \fBConfigTheme::theme_fade_color\fP\fC [private]\fP"
.SS "string \fBConfigTheme::theme_floor_color_1\fP\fC [private]\fP"
.SS "string \fBConfigTheme::theme_floor_color_2\fP\fC [private]\fP"
.SS "string \fBConfigTheme::theme_heading_color\fP\fC [private]\fP"
.SS "string \fBConfigTheme::theme_overlay_image\fP\fC [private]\fP"
.SS "string \fBConfigTheme::theme_wall_color_1\fP\fC [private]\fP"
.SS "string \fBConfigTheme::theme_wall_color_2\fP\fC [private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
