.TH "configinput.cpp" 3 "Wed Aug 22 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configinput.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'configinput\&.h'\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static string \fBjoystickNameWithoutNumber\fP (string joystickName)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const string \fBDEFAULTJOYSTICKPORT0\fP = 'mouse'"
.br
.ti -1c
.RI "const string \fBDEFAULTJOYSTICKPORT1\fP = 'keyboard'"
.br
.ti -1c
.RI "const string \fBDEFAULTJOYSTICKPORT\fP = 'none'"
.br
.ti -1c
.RI "const string \fBDEFAULTJOYSTICKPORTMODE\fP = ''"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static string \fBjoystickNameWithoutNumber\fP (stringjoystickName)\fC [static]\fP"
.SH "Variable Documentation"
.PP 
.SS "const string \fBDEFAULTJOYSTICKPORT\fP = 'none'"
.SS "const string \fBDEFAULTJOYSTICKPORT0\fP = 'mouse'"
.SS "const string \fBDEFAULTJOYSTICKPORT1\fP = 'keyboard'"
.SS "const string \fBDEFAULTJOYSTICKPORTMODE\fP = ''"
.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
