.TH "configcdrom.h" 3 "Wed Aug 22 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configcdrom.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigCDRom\fP"
.br
.RI "\fIOn the success of the A500, Commodore launches in the production of alternative projects, that are based on the \fBAmiga\fP\&. The 'CDTV', of 1990, is designed as a household appliance for multimedia entertainment, and is basically an A500 with a CD-Rom, in a chassis similar to that of a VCR\&. 
.br
 The intention of the Commodore, the CDTV must implement the convergence of television and computers, allowing the user to play games, watch movies and listen to music with the same equipment, the most advanced user can then expand the purchasing CDTV keyboard, floppy disk drives, and mouse and turn it into an actual computer\&.
.br
 AmigaCD32 (1993), is instead a console dedicated to video games, equipped with 68020 processor with 32-bit architecture and is based on the use of a CD-Rom integrated\&. 
.br
 
.br
 CD This class is responsible for the Cd-Rom Configuration\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
