.TH "configtheme.cpp" 3 "Wed Aug 22 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configtheme.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'configtheme\&.h'\fP
.br
\fC#include <QRegExp>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const string \fBDEFAULTTHEME\fP = ''"
.br
.ti -1c
.RI "const string \fBDEFAULTTHEMEFADECOLOR\fP = '#3c3b37'"
.br
.ti -1c
.RI "const string \fBDEFAULTTHEMEWALLCOLOR\fP = '#3c3b37'"
.br
.ti -1c
.RI "const string \fBDEFAULTTHEMEFLOORCOLOR1\fP = '#1d1d1b'"
.br
.ti -1c
.RI "const string \fBDEFAULTTHEMEFLOORCOLOR2\fP = '#111110'"
.br
.ti -1c
.RI "const string \fBDEFAULTTHEMEHEADINGCOLOR\fP = '#f68355'"
.br
.ti -1c
.RI "const string \fBDEFAULTTHEMEOVERLAYIMAGE\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBconfigtheme\&.cpp\fP
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc\&., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA\&. Written by Riva Alessandro Mario, alessandromario.riva@gmail.com and Sanvito Davide, dsanvito90@gmail.com\&. 
.SH "Variable Documentation"
.PP 
.SS "const string \fBDEFAULTTHEME\fP = ''"
.SS "const string \fBDEFAULTTHEMEFADECOLOR\fP = '#3c3b37'"
.SS "const string \fBDEFAULTTHEMEFLOORCOLOR1\fP = '#1d1d1b'"
.SS "const string \fBDEFAULTTHEMEFLOORCOLOR2\fP = '#111110'"
.SS "const string \fBDEFAULTTHEMEHEADINGCOLOR\fP = '#f68355'"
.SS "const string \fBDEFAULTTHEMEOVERLAYIMAGE\fP = ''"
.SS "const string \fBDEFAULTTHEMEWALLCOLOR\fP = '#3c3b37'"
.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
