.TH "configram.cpp" 3 "Fri Jul 27 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configram.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'configram\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const string \fBDEFAULTCHIPMEMORY\fP = '512'"
.br
.ti -1c
.RI "const string \fBDEFAULTSLOWMEMORY\fP = 'NONE'"
.br
.ti -1c
.RI "const string \fBDEFAULTFASTMEMORY\fP = 'NONE'"
.br
.ti -1c
.RI "const string \fBDEFAULTZORROIIIMEMORY\fP = 'NONE'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const string \fBDEFAULTCHIPMEMORY\fP = '512'"
.SS "const string \fBDEFAULTFASTMEMORY\fP = 'NONE'"
.SS "const string \fBDEFAULTSLOWMEMORY\fP = 'NONE'"
.SS "const string \fBDEFAULTZORROIIIMEMORY\fP = 'NONE'"
.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
