.TH "Ui" 3 "Mon Aug 6 2012" "Version 1.0" "FS-UAE Gui for Linux OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui \- 
.PP
Create a new main window: \fBAmiga\fP Gui\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Create a new main window: \fBAmiga\fP Gui\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for FS-UAE Gui for Linux OS from the source code\&.
